repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
        exclude: ^conda.recipe/
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: flake8
    -   id: mixed-line-ending
    -   id: sort-simple-yaml
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
    - id: ruff
